//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeConsumer.SoapWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapWebService.ChequeSOAPServiceSoap")]
    public interface ChequeSOAPServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllMenuItemsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMenuItems", ReplyAction="*")]
        ChequeConsumer.SoapWebService.GetAllMenuItemsResponse GetAllMenuItems(ChequeConsumer.SoapWebService.GetAllMenuItemsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMenuItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMenuItems", Namespace="http://tempuri.org/", Order=0)]
        public ChequeConsumer.SoapWebService.GetAllMenuItemsRequestBody Body;
        
        public GetAllMenuItemsRequest() {
        }
        
        public GetAllMenuItemsRequest(ChequeConsumer.SoapWebService.GetAllMenuItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMenuItemsRequestBody {
        
        public GetAllMenuItemsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMenuItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMenuItemsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChequeConsumer.SoapWebService.GetAllMenuItemsResponseBody Body;
        
        public GetAllMenuItemsResponse() {
        }
        
        public GetAllMenuItemsResponse(ChequeConsumer.SoapWebService.GetAllMenuItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMenuItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllMenuItemsResult;
        
        public GetAllMenuItemsResponseBody() {
        }
        
        public GetAllMenuItemsResponseBody(string GetAllMenuItemsResult) {
            this.GetAllMenuItemsResult = GetAllMenuItemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChequeSOAPServiceSoapChannel : ChequeConsumer.SoapWebService.ChequeSOAPServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChequeSOAPServiceSoapClient : System.ServiceModel.ClientBase<ChequeConsumer.SoapWebService.ChequeSOAPServiceSoap>, ChequeConsumer.SoapWebService.ChequeSOAPServiceSoap {
        
        public ChequeSOAPServiceSoapClient() {
        }
        
        public ChequeSOAPServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChequeSOAPServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeSOAPServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeSOAPServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChequeConsumer.SoapWebService.GetAllMenuItemsResponse ChequeConsumer.SoapWebService.ChequeSOAPServiceSoap.GetAllMenuItems(ChequeConsumer.SoapWebService.GetAllMenuItemsRequest request) {
            return base.Channel.GetAllMenuItems(request);
        }
        
        public string GetAllMenuItems() {
            ChequeConsumer.SoapWebService.GetAllMenuItemsRequest inValue = new ChequeConsumer.SoapWebService.GetAllMenuItemsRequest();
            inValue.Body = new ChequeConsumer.SoapWebService.GetAllMenuItemsRequestBody();
            ChequeConsumer.SoapWebService.GetAllMenuItemsResponse retVal = ((ChequeConsumer.SoapWebService.ChequeSOAPServiceSoap)(this)).GetAllMenuItems(inValue);
            return retVal.Body.GetAllMenuItemsResult;
        }
    }
}
